### ISSUE TITLE
[FEAT]: StackView를 통한 페이지 스와이프 기능 도입 및 MVVM 아키텍쳐 전환

### ISSUE THREAD

**Issue by yudonlee** [yudonlee/ChulChulHanyang#41]
## 💡 Issue

1. 출출하냥 구조 개선(MVC => MVVM)
- MVC구조 내에서 데이터 reload, refresh control, network error등 다양한 상황을 대응하는 ViewController 로직 비대화
- 데이터 flow의 복잡도의 따른 유지보수 난이도 상승 
- 가독성이 떨어지는 코드
- Test Code작성의 어려움 
위를 해결하기 위해 단방향 데이터 흐름을 적용한 MVVM 구조 도입
2. StackView + ScrollView로 뷰 개편(Swipe를 통한 식당 이동)
- 식당 카테고리 버튼을 통해서만 식당 이동이 가능하여 사용성 저하
- 매번 식당들을 전환할 때 마다 Reload되어야 하는 문제

## 📝  todo
- [ ] StackView + ScrollView로 MainView 개편
- [ ] Combine을 활용하여 StackView의 View들을 위한 ViewModel 도입
- [ ] ViewModel을 Flux 아키텍쳐 적용(Reactorkit 적용)
